### ISSUE TITLE
Biquad::SetGain(float value) clamps incorrectly

### ISSUE THREAD

**Issue by markheath** [GhostNoteAudio/CloudSeedCore#1]
Spotted this while browsing through the codebase. It looks like a bug to me - should test for greater than, not less than
https://github.com/GhostNoteAudio/CloudSeedCore/blob/0b252c8ee74414f173946debfaabce89b9c4a8c6/DSP/Biquad.cpp#L88

**Comment by godofecht** [comment]
Just submitted a PR.

I think this was the kind of typo std::clamp was dseigned to prevent.

**Comment by godofecht** [comment]
@GhostNoteAudio we can close this issue, it was handled in commit [9ca9f7d](https://github.com/GhostNoteAudio/CloudSeedCore/commit/9ca9f7df6e4b37b6bf84a0f5233f657426328e69)
