### ISSUE TITLE
Samplerate should be Double, not Integer

### ISSUE THREAD

**Issue by godofecht** [GhostNoteAudio/CloudSeedCore#3]
https://github.com/GhostNoteAudio/CloudSeedCore/blob/9ca9f7df6e4b37b6bf84a0f5233f657426328e69/DSP/AllpassDiffuser.h#L37

I noticed that the sample rate was an integer. Probably makes sense to swap it out for a double... correct me if I'm wrong. If all is well, I'll submit a PR in the next few days :)

**Comment by GhostNoteAudio** [comment]
Probably not ideal to make it a double. It's a bit mixed whether the modules have int or float as samplerate. It should probably be int everywhere to be honest, as fractional samplerate is not very common and a has some gotchas. 

If you were to make a PR for that, I'm not sure I can expend the time reviewing and checking the behaviour of all the modules, I just don't have the time for it right now. In the best case, the PR would result in no change; at worst, it would break in some unexpected way.

**Comment by godofecht** [comment]
Thanks for clarifying!
